# Generated by Django 3.2.6 on 2021-08-25 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CATEGORIES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.CharField(max_length=3)),
                ('categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCTS',
            fields=[
                ('id_producto', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombredelproducto', models.CharField(max_length=50)),
                ('proveedor', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DISCOUNT',
            fields=[
                ('id_producto', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('precio', models.CharField(max_length=10)),
                ('descuento', models.PositiveIntegerField(default=5)),
                ('PRODUCTS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.products')),
            ],
        ),
    ]
